name: MeroBot

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}  # استخدم التوكن هنا

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the script
        env:
          MEROBOT_TOKEN: ${{ secrets.MEROBOT_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python update_readme.py

      - name: Commit and push changes
        run: |
          git config --global user.name "MeroBot"
          git config --global user.email "merobot@example.com"
          git add README.md
          git commit -m "Update activity feed"
          git push https://github.com/Meronave/Meronave.git HEAD:main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
